### ISSUE TITLE
用自己训练的模型文件

### ISSUE THREAD

**Issue by Trevo1** [z1069614715/yolov7-pyqt#1]
up你好，我用自己训练的文件来推理，报的这个错
Traceback (most recent call last):
  File "run_gui.py", line 166, in begin_detect
    image_det = self.model(self.now)
  File "E:\PROJECT\yolov7-pyqt-master\yolo.py", line 36, in __call__
    image = self.post_processing(result, im, image)
  File "E:\PROJECT\yolov7-pyqt-master\yolo.py", line 65, in post_processing
    result[:, :4] -= np.array(dwdh * 2)
ValueError: operands could not be broadcast together with shapes (1,4,20,20) (4,) (1,4,20,20)

**Comment by z1069614715** [comment]
yolov7用的是我提供的代码进行训练吗？

**Comment by Trevo1** [comment]
不是 我用的别人写的yolov7代码，就是把模型文件拿过来用了 跑你的模型是可以的...
在别人代码上写了pyqt的界面 但是模型推理的不知道怎么写了 所以想拿到你代码上试试 结果是不行的

**Comment by z1069614715** [comment]
那应该是yiolov7的版本问题，这种我没法帮你看，需要自行解决

**Comment by Trevo1** [comment]
好的 谢谢

**Comment by Trevo1** [comment]
请问up你的yolov7训练代码在哪呢 我想用你的代码训练一下

**Comment by z1069614715** [comment]
B站可以找到.
